platform :ios, '7.0'
pod 'ACPButton'
pod 'NHBalancedFlowLayout', '~> 0.2'
pod 'LXReorderableCollectionViewFlowLayout', '~> 0.1.1'
pod 'ILTranslucentView', '~> 0.0'
pod 'STTweetLabel', '~> 3.1'
pod 'PBWebViewController', '~> 0.2'