platform :ios, '7.0'
pod 'REFrostedViewController', '~> 2.4.2'
pod 'ACPButton'
pod 'NHBalancedFlowLayout', '~> 0.2'
pod 'LXReorderableCollectionViewFlowLayout', '~> 0.1.1'
pod 'ILTranslucentView', '~> 0.0'
pod 'Reachability', '~> 3.1'